package iuh.fit.airsky.exception;

public enum ErrorCode {
    INVALID_TOKEN_OR_NOT_LOGGED_IN,
    FORBIDDEN,
    ROUTE_NOT_FOUND,
    METHOD_NOT_ALLOWED,
    RESOURCE_NOT_FOUND,
    USER_ALREADY_EXISTS,
    INVALID_CREDENTIALS,
    EMAIL_NOT_VERIFIED,
    INVALID_OTP,
    DB_CONSTRAINT_VIOLATION,
    VALIDATION_FAILED,
    UNEXPECTED_ERROR
}
