package iuh.fit.airsky.service.impl;

import iuh.fit.airsky.dto.response.SeatResponse;
import iuh.fit.airsky.enums.SeatStatus;
import iuh.fit.airsky.exception.ResourceNotFoundException;
import iuh.fit.airsky.mapper.SeatMapper;
import iuh.fit.airsky.model.*;
import iuh.fit.airsky.repository.AircraftRepository;
import iuh.fit.airsky.repository.FlightRepository;
import iuh.fit.airsky.repository.FlightTravelClassRepository;
import iuh.fit.airsky.repository.PassengerRepository;
import iuh.fit.airsky.repository.SeatRepository;
import iuh.fit.airsky.repository.TravelClassRepository;
import iuh.fit.airsky.service.SeatService;
import iuh.fit.airsky.util.SeatGeneratorUtil;
import jakarta.persistence.EntityNotFoundException;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.List;
import java.util.concurrent.ConcurrentHashMap;

@RequiredArgsConstructor
@Service
@Slf4j
public class SeatServiceImpl implements SeatService {

    private final SeatRepository seatRepository;
    private final SeatMapper seatMapper;
    private final TravelClassRepository travelClassRepository;
    private final PassengerRepository passengerRepository;
    private final AircraftRepository aircraftRepository;
    private final FlightRepository flightRepository;
    private final FlightTravelClassRepository flightTravelClassRepository;
    // Lock map theo flightId
    private final ConcurrentHashMap<Long, Object> flightLocks = new ConcurrentHashMap<>();

    @Override
    @Transactional(readOnly = true)
    public List<SeatResponse> getSeatsByFlight(Long flightId) {
        // Try to get seats from cache first
        List<Seat> seats = seatRepository.findByFlightId(flightId);
        
        if (!seats.isEmpty()) {
            log.debug("Returning {} cached seats for flight {}", seats.size(), flightId);
            return mapToSeatResponses(seats);
        }

        // Lazy seat generation with lock
        Object lock = flightLocks.computeIfAbsent(flightId, k -> new Object());
        
        synchronized (lock) {
            try {
                // Double-check after acquiring lock
                seats = seatRepository.findByFlightId(flightId);
                if (!seats.isEmpty()) {
                    log.debug("Seats already generated by another thread for flight {}", flightId);
                    return mapToSeatResponses(seats);
                }

                log.info("Generating seats for flight {}", flightId);
                seats = generateAndSaveSeats(flightId);
                log.info("Successfully generated {} seats for flight {}", seats.size(), flightId);
                
                return mapToSeatResponses(seats);
            } finally {
                // Always remove the lock to prevent memory leak
                flightLocks.remove(flightId);
            }
        }
    }
    
    private List<Seat> generateAndSaveSeats(Long flightId) {
        // Get flight with aircraft and travel classes in one query
        Flight flight = flightRepository.findByIdWithAircraftAndTravelClasses(flightId)
                .orElseThrow(() -> new ResourceNotFoundException("Flight not found with id: " + flightId));

        // Verify aircraft exists
        if (flight.getAircraft() == null) {
            throw new IllegalStateException("No aircraft assigned to flight " + flightId);
        }

        // Verify FlightTravelClasses exist
        if (flight.getFlightTravelClasses() == null || flight.getFlightTravelClasses().isEmpty()) {
            throw new IllegalStateException("No flight travel classes found for flight " + flightId + 
                    ". Make sure travel classes are created first.");
        }

        // Get all travel classes for reference
        List<TravelClass> travelClasses = travelClassRepository.findAll();
        if (travelClasses.isEmpty()) {
            throw new IllegalStateException("No travel classes found");
        }

        log.info("Generating seats for flight {} with {} travel classes", 
                flightId, flight.getFlightTravelClasses().size());
        
        // Log capacity information for debugging
        for (var ftc : flight.getFlightTravelClasses()) {
            log.info("Travel class: {} - Capacity: {}", 
                    ftc.getTravelClass().getClassName(), ftc.getCapacity());
        }

        // Generate and save seats in batch
        List<Seat> seats = SeatGeneratorUtil.generateSeats(flight, flight.getAircraft(), travelClasses);
        log.info("Generated {} seats total for flight {}", seats.size(), flightId);
        
        // Save seats
        List<Seat> savedSeats = seatRepository.saveAll(seats);
        
        // Save updated flight travel classes with correct capacities
        flightTravelClassRepository.saveAll(flight.getFlightTravelClasses());
        log.info("Updated flight travel class capacities for flight {}", flightId);
        
        return savedSeats;
    }
    
    private List<SeatResponse> mapToSeatResponses(List<Seat> seats) {
        return seats.stream()
                .map(seatMapper::toResponseDTO)
                .toList();
    }

    @Override
    @Transactional(readOnly = true)
    public List<SeatResponse> getSeatsByFlightIdAndTravelClassId(Long flightId, Long travelClassId) {
        // First try to get seats for specific travel class
        List<Seat> seats = seatRepository.findByFlightIdAndTravelClassId(flightId, travelClassId);
        
        if (!seats.isEmpty()) {
            log.debug("Returning {} seats for flight {} and travel class {}", 
                    seats.size(), flightId, travelClassId);
            return mapToSeatResponses(seats);
        }
        
        // If no seats found, generate all seats for the flight
        getSeatsByFlight(flightId);
        
        // Try to get seats again after generation
        seats = seatRepository.findByFlightIdAndTravelClassId(flightId, travelClassId);
        if (seats.isEmpty()) {
            log.warn("No seats found for flight {} and travel class {} after generation", 
                    flightId, travelClassId);
        }
        
        return mapToSeatResponses(seats);
    }

    @Override
    @Transactional
    public void createSeatsForFlight(Flight flight) {
        if (flight == null || flight.getFlightId() == null) {
            throw new IllegalArgumentException("Flight and flight ID must not be null");
        }

        Long flightId = flight.getFlightId();
        Object lock = flightLocks.computeIfAbsent(flightId, k -> new Object());
        
        synchronized (lock) {
            try {
                // Check if seats already exist
                if (!seatRepository.findByFlight(flight).isEmpty()) {
                    log.debug("Seats already exist for flight {}", flightId);
                    return;
                }

                // Generate and save seats
                List<Seat> seats = generateAndSaveSeats(flightId);
                log.info("Successfully created {} seats for flight {}", seats.size(), flightId);
            } finally {
                flightLocks.remove(flightId);
            }
        }
    }

    // Ví dụ cho book seat an toàn (nhiều người cùng lúc)
    @Transactional
    public void bookSeats(Long flightId, List<String> seatNumbers, Long passengerId) {
        for (String seatNumber : seatNumbers) {
            List<Seat> seats = seatRepository.findByFlightIdAndSeatNumberForUpdate(flightId, seatNumber);
            
            if (seats.isEmpty()) {
                throw new RuntimeException("Seat not found: " + seatNumber);
            }
            
            if (seats.size() > 1) {
                throw new RuntimeException("Multiple seats found for seat number: " + seatNumber + ". Found " + seats.size() + " seats.");
            }
            
            Seat seat = seats.get(0);

            if (seat.getStatus() != SeatStatus.AVAILABLE) {
                throw new RuntimeException("Seat already booked: " + seatNumber);
            }

            Passenger passenger = passengerRepository.findById(passengerId)
                    .orElseThrow(() -> new RuntimeException("Passenger not found"));

            seat.setBookedByPassenger(passenger);
            seat.setStatus(SeatStatus.PENDING_PAYMENT); // Đặt trạng thái chờ thanh toán thay vì BOOKED ngay lập tức


            seatRepository.save(seat);
        }
    }
}
